### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by nateandre** [csc309project/GameFinder#30]
Improper spacing not conforming to html standards for some p,ul,li,div tags which could lead to readability issues down the line.

Locations:
GameFinder/workingBuild/single_game.html
GameFinder/workingBuild/search_results.html
GameFinder/workingBuild/search.html
GameFinder/workingBuild/log_in.html

**Comment by jeremyryan5** [comment]
No longer using those files, fixed in new files.
